stages:
  - install
  - test
  - deploy

variables:
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY  
  SSH_USER: "yared"
  SERVER_IP: "54.160.180.69"

install:
  stage: install
  script:
    - npm install
  only:
    - development

test:
  stage: test
  script:
    - npm test  
  only:
    - development

deploy:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
    - |
      ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP << 'EOF'
        cd /response-question/question-response-service  
        git pull origin development
        npm install
        pm2 restart all
      EOF
  only:
    - development

  tags:
   - kifiya_docker_runner01


