stages:
  - build
  - deploy
  - cleanup

development-build:
  stage: build
  tags:
    - kft_build_server01
  only:
    - development
  script:
    - >
      docker build
      -t "$DOCKER_REGISTRY_URL"/platform-x/backend/"${CI_PROJECT_NAME}"_"${CI_COMMIT_BRANCH}"_img .
    - echo "$DOCKER_REGISTRY_PASS" | docker login "$DOCKER_REGISTRY_URL" --username $DOCKER_REGISTRY_USER --password-stdin
    - docker push "$DOCKER_REGISTRY_URL"/platform-x/backend/"${CI_PROJECT_NAME}"_"${CI_COMMIT_BRANCH}"_img

deploy:
  stage: deploy
  only:
    - development
  tags:
    - kft_build_server01
  script:
    - ansible-playbook ~/../kifiya/workspace/ansible-playbooks/Platform-X/Backend/"${CI_PROJECT_NAME}"_"${CI_COMMIT_BRANCH}".yml
  retry: 2

cleanup:
  stage: cleanup
  only:
    - development
  tags:
    - kft_build_server01
  script:
    - docker image prune -af
  retry: 2
